(function(){
  const KEY='d365fo-practice-lab-phase5-v1';
  const VERSION='5.0';
  const src={
    learn:'https://learn.microsoft.com/en-us/training/paths/develop-x-plus-plus-finance-operations/',
    ext:'https://learn.microsoft.com/en-us/dynamics365/fin-ops-core/dev-itpro/extensibility/writing-extensible-code',
    coc:'https://learn.microsoft.com/en-us/dynamics365/fin-ops-core/dev-itpro/extensibility/method-wrapping-coc',
    update:'https://learn.microsoft.com/en-us/dynamics365/fin-ops-core/dev-itpro/dev-ref/xpp-data/xpp-update',
    classExt:'https://learn.microsoft.com/en-us/dynamics365/fin-ops-core/dev-itpro/extensibility/class-extensions',
    entities:'https://learn.microsoft.com/en-us/dynamics365/fin-ops-core/dev-itpro/data-entities/data-entities',
    sysop:'https://learn.microsoft.com/en-us/dynamics365/fin-ops-core/dev-itpro/dev-tools/sysoperation-framework',
    unit:'https://learn.microsoft.com/en-us/dynamics365/fin-ops-core/dev-itpro/perf-test/testing-validation'
  };
  const seed=()=>({version:VERSION,done:{},attempts:{},notes:{},score:0,last:'syntax'});
  let s=load();
  function load(){try{return Object.assign(seed(),JSON.parse(localStorage.getItem(KEY)||'{}'))}catch(e){return seed()}}
  function save(){localStorage.setItem(KEY,JSON.stringify(s))}
  function esc(v){return String(v??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[m]))}
  function set(html,path){const p=document.querySelector('#page');if(!p)return;p.innerHTML='<div class="page-wrap p5-shell">'+html+'</div>';const c=document.querySelector('#breadcrumb');if(c)c.textContent=path||'Developer > X++ Developer Lab'}
  function pct(){return Math.round(Object.values(s.done).filter(Boolean).length/lessons.length*100)}
  const lessons=[
    {id:'syntax',n:1,title:'X++ temelleri ve OOP',level:'Foundation',desc:'Types, loops, methods, classes, access modifiers, exceptions, collections.',path:'Visual Studio > Application Explorer > Classes',source:src.learn},
    {id:'metadata',n:2,title:'AOT, model, package, table, EDT, enum',level:'Foundation',desc:'Metadata-first tasarım, table/EDT/relation/index mantığı ve naming.',path:'Visual Studio > Application Explorer',source:src.learn},
    {id:'query',n:3,title:'Select, joins ve query tasarımı',level:'Core',desc:'exists join, notexists join, field list, order by, aggregation ve N+1 önleme.',path:'X++ data access',source:src.learn},
    {id:'transaction',n:4,title:'Transactions, forUpdate, ttsLevel',level:'Core',desc:'ttsBegin/ttsCommit scope, optimistic concurrency ve update conflict yaklaşımı.',path:'X++ transactional integrity',source:src.update},
    {id:'setbased',n:5,title:'Set-based işlemler ve performans',level:'Core',desc:'update_recordset/insert_recordset, row-by-row maliyeti, business logic trade-off.',path:'X++ data update',source:src.update},
    {id:'extension',n:6,title:'Extension-first, CoC, event handler',level:'Core',desc:'Overlayering yerine extension, next çağrısı, doğru extension point seçimi.',path:'Application Suite extension',source:src.coc},
    {id:'sysop',n:7,title:'SysOperation ve batch',level:'Mid',desc:'Contract/controller/service ayrımı, batch-safe tasarım ve idempotency.',path:'System administration > Batch jobs',source:src.sysop},
    {id:'entity',n:8,title:'Data Entity, OData ve validation',level:'Mid',desc:'Entity boundary, staging, validation, integration-safe iş kuralları.',path:'Data management workspace',source:src.entities},
    {id:'security',n:9,title:'Security-aware development',level:'Mid',desc:'Privilege/duty/role etkisi, authorization boundary ve bypass anti-patternleri.',path:'System administration > Security',source:src.ext},
    {id:'testing',n:10,title:'Unit test, test seam ve regression',level:'Mid',desc:'Arrange-Act-Assert, deterministic test data, boundary cases ve negative tests.',path:'Test project / SysTest',source:src.unit},
    {id:'review',n:11,title:'Code review ve performance clinic',level:'Mid',desc:'Query count, field projection, transaction scope, retry, error handling, readability.',path:'Peer review / pull request',source:src.ext},
    {id:'capstone',n:12,title:'Techno-functional X++ capstone',level:'Mid+',desc:'Finance/SCM talebini standard-vs-custom analiziyle tasarla, uygula, test et.',path:'Requirement > design > implementation > UAT',source:src.ext}
  ];
  const labs={
    syntax:{title:'Talep: yüksek tutarlı vendor invoice kontrolü',context:'Finance ekibi 100.000 TRY üstü vendor invoice post edilirken açıklama alanı boşsa kullanıcıya anlaşılır hata verilmesini istiyor.',problem:'Kontrolün form butonuna yazılması batch, import veya farklı posting yollarını kaçırabilir.',request:'Kontrolü doğru business-layer extension point üzerinde tasarla. Magic number kullanma; şirket bazlı parametre düşün.',question:'Aşağıdaki method iskeletini readable ve maintainable hale getir.',starter:`class TBInvoicePolicy\n{\n    public boolean validate(AmountCur _amount, str _description)\n    {\n        // TODO\n        return true;\n    }\n}`,
      checks:[['hasThreshold',/100000|threshold|limit/i,'Threshold veya konfigüre edilebilir limit düşünülmüş mü?'],['hasDesc',/description|strLen|empty|blank/i,'Açıklama kontrolü var mı?'],['returns',/return/i,'Deterministic return var mı?']],solution:'Policy/parameter sınıfından limit oku; validation metodunu posting sürecinin gerçek business boundary noktasından çağır; kullanıcı mesajını label ile ver. UI-only validation yapma.',source:src.ext},
    metadata:{title:'Talep: vendor üzerinde RiskCategory alanı',context:'Satınalma ekibi vendor master üzerinde A/B/C risk kategorisi istiyor ve bu değer raporlanacak.',problem:'Serbest metin alanı veri kalitesini bozar. Base table modifikasyonu upgrade riskidir.',request:'EDT + enum + table extension + form extension tasarla.',question:'Hangi artifactları oluşturacağını ve ilişkilerini kod/not olarak yaz.',starter:`// Artifacts\n// 1. Enum: ?\n// 2. EDT: ?\n// 3. VendTable extension field: ?\n// 4. Form extension: ?`,checks:[['enum',/enum/i,'Enum kullanılıyor mu?'],['edt',/edt|extended data type/i,'EDT düşünülmüş mü?'],['extension',/extension|ExtensionOf/i,'Extension-first yaklaşım var mı?']],solution:'Extensible enum + EDT + VendTable extension field + VendTable form extension. Label ve help text ekle; gerekirse index/reporting ihtiyacını değerlendir.',source:src.classExt},
    query:{title:'Sorun: 50.000 vendor satırında N+1 query',context:'Gece batch’i vendor başına ayrı bir open transaction sorgusu çalıştırıyor ve 40 dakika sürüyor.',problem:'Loop içindeki select, SQL round-trip sayısını patlatıyor.',request:'Tek query/join veya set-based yaklaşım ile yeniden tasarla.',question:'Kodda N+1’i kaldır ve yalnız gerekli alanları seç.',starter:`VendTable vendTable;\nVendTrans vendTrans;\nwhile select AccountNum from vendTable\n{\n    select firstOnly RecId from vendTrans\n        where vendTrans.AccountNum == vendTable.AccountNum\n           && vendTrans.Closed == dateNull();\n}`,checks:[['join',/join|exists join/i,'Join/exists join kullanıldı mı?'],['field',/AccountNum|RecId/i,'Field projection düşünülmüş mü?'],['noNested',!/while[\s\S]*select firstOnly[\s\S]*where/i,'Loop içinde ikinci select kaldırıldı mı?']],solution:`while select AccountNum from vendTable\n    exists join RecId from vendTrans\n        where vendTrans.AccountNum == vendTable.AccountNum\n           && vendTrans.Closed == dateNull()\n{\n    // process vendor once\n}` ,source:src.learn},
    transaction:{title:'Sorun: kısmi veri güncellemesi',context:'Custom approval sırasında header update oluyor, line update hata veriyor ve sistem yarım durumda kalıyor.',problem:'Transaction scope business unit-of-work ile hizalı değil.',request:'forUpdate + tts scope ile atomik hale getir.',question:'Transaction sınırını düzelt; catch içinde veriyi elle “tamamlama” yapma.',starter:`select forUpdate myHeader where myHeader.RecId == _id;\nmyHeader.Status = MyStatus::Approved;\nmyHeader.update();\n\nselect forUpdate myLine where myLine.Header == _id;\nmyLine.Processed = NoYes::Yes;\nmyLine.update();`,checks:[['tts',/ttsBegin[\s\S]*ttsCommit/i,'ttsBegin/ttsCommit aynı unit-of-work etrafında mı?'],['forupdate',/forUpdate/i,'forUpdate kullanılıyor mu?'],['catch',!/catch[\s\S]*update/i,'Catch içinde tehlikeli telafi update’i yok mu?']],solution:`ttsBegin;\nselect forUpdate myHeader where myHeader.RecId == _id;\nselect forUpdate myLine where myLine.Header == _id;\nmyHeader.Status = MyStatus::Approved;\nmyHeader.update();\nmyLine.Processed = NoYes::Yes;\nmyLine.update();\nttsCommit;`,source:src.update},
    setbased:{title:'Performance: 200.000 kaydı işaretleme',context:'Bir maintenance job aynı flag’i 200.000 satırda tek tek update ediyor.',problem:'Row-by-row update pahalı. Ancak table update() business logic varsa körlemesine set-based geçmek de riskli.',request:'Önce business logic bağımlılığını değerlendir; uygunsa update_recordset kullan.',question:'Performanslı çözüm yaz ve hangi durumda kullanmaman gerektiğini not et.',starter:`while select forUpdate myTable where myTable.Status == Status::Old\n{\n    myTable.Status = Status::Archived;\n    myTable.update();\n}` ,checks:[['set',/update_recordset/i,'Set-based update kullanılıyor mu?'],['where',/where/i,'Scope filtreli mi?'],['logic',/business|update\(\)|event|CoC|handler/i,'Business logic bypass riskine değinilmiş mi?']],solution:`update_recordset myTable\n    setting Status = Status::Archived\n    where myTable.Status == Status::Old;\n\n// Ancak update() / handlers / CoC iş mantığı gerekiyorsa set-based dönüşüm davranışını doğrula. doUpdate() ile bypass etme.`,source:src.update},
    extension:{title:'Talep: Sales order confirm öncesi ek kontrol',context:'Şirket satış siparişi confirm edilirken özel kredi onayı yoksa durdurmak istiyor.',problem:'Base class değiştirmek upgrade-safe değil. Form button handler batch/API yollarını kaçırabilir.',request:'Uygun public/protected business method için Chain of Command tasarla.',question:'CoC iskeleti yaz; next çağrısını doğru kullan.',starter:`// ExtensionOf(...)\nfinal class TBSalesConfirm_Extension\n{\n    // TODO\n}` ,checks:[['extensionof',/ExtensionOf/i,'ExtensionOf attribute var mı?'],['final',/final class/i,'Extension class final mı?'],['next',/next\s+/i,'next çağrısı var mı?']],solution:`[ExtensionOf(classStr(SomeSalesConfirmClass))]\nfinal class TBSalesConfirm_Extension\n{\n    public void run()\n    {\n        this.validateCustomCreditApproval();\n        next run();\n    }\n}` ,source:src.coc},
    sysop:{title:'Talep: gece vendor risk skoru hesaplama batch’i',context:'10.000 vendor için hesaplama kullanıcı oturumundan bağımsız ve tekrar çalıştırılabilir olmalı.',problem:'Runnable class içinde her şeyi yapmak testability ve batch operasyonunu zorlaştırır.',request:'DataContract + Service + Controller ayrımı ve idempotent processing tasarla.',question:'Sınıf sorumluluklarını yaz ve retry durumunda double-processing’i nasıl önleyeceğini açıkla.',starter:`// Contract: parameters\n// Service: business operation\n// Controller: execution/batch\n// Idempotency key/check: ?`,checks:[['contract',/contract/i,'Contract sorumluluğu var mı?'],['service',/service/i,'Service ayrımı var mı?'],['controller',/controller/i,'Controller ayrımı var mı?'],['idem',/idempot|already|processed|key/i,'Idempotency düşünülmüş mü?']],solution:'Contract yalnız parametreleri taşır; Service transaction/business logic’i çalıştırır; Controller menu item/batch orchestration sağlar. Her vendor+asOfDate için process marker veya deterministic upsert kullan.',source:src.sysop},
    entity:{title:'Integration: vendor import invalid group',context:'OData üzerinden vendor geliyor; geçersiz VendorGroup ile kayıt alınmamalı.',problem:'Sadece form-level validation entegrasyon yolunu korumaz.',request:'Validation’ı entity/table business boundary’de merkezi tut.',question:'Hangi katmanda neyi kontrol edeceğini açıkla.',starter:`// Entity validation:\n// Table validation:\n// Error contract:\n`,checks:[['entity',/entity/i,'Entity validation düşünülmüş mü?'],['table',/table|validateWrite/i,'Table/business invariant düşünülmüş mü?'],['error',/error|message|label/i,'Anlaşılır hata düşünülmüş mü?']],solution:'Integration-spesifik mapping/shape validation entity’de; tüm yazma yolları için geçerli invariant table/business logic katmanında. Form-only kontrol yeterli değildir.',source:src.entities},
    security:{title:'Security: custom “Approve payment” action',context:'Yeni buton sadece Treasury Approver rolüne açık olmalı.',problem:'Kod içinde userId hardcode etmek veya System administrator kontrolü yapmak bakım ve SoD açısından yanlıştır.',request:'Menu item + privilege + duty + role ile least-privilege tasarla.',question:'Security artifact zincirini yaz.',starter:`// Entry point: menu item\n// Privilege: ?\n// Duty: ?\n// Role: ?`,checks:[['priv',/privilege/i,'Privilege var mı?'],['duty',/duty/i,'Duty var mı?'],['role',/role/i,'Role var mı?'],['nohard',!/userId\s*==|sysadmin/i,'Hard-coded kullanıcı kontrolünden kaçınılıyor mu?']],solution:'Action menu item oluştur; privilege ile entry point access tanımla; privilege’ı uygun duty’ye, duty’yi Treasury Approver role’e ekle. Kod içinde kullanıcı adı hardcode etme.',source:src.ext},
    testing:{title:'Test: 100K invoice threshold policy',context:'Yeni policy deployment öncesi regression test isteniyor.',problem:'Sadece happy-path test sınır değer hatalarını kaçırır.',request:'99.999,99 / 100.000 / 100.000,01 ve boş açıklama kombinasyonlarını test et.',question:'AAA mantığıyla test case planını yaz.',starter:`// Arrange\n// Act\n// Assert\n// Cases:\n`,checks:[['arrange',/arrange/i,'Arrange var mı?'],['act',/act/i,'Act var mı?'],['assert',/assert/i,'Assert var mı?'],['boundary',/99999|100000|100001|boundary/i,'Boundary case var mı?']],solution:'Boundary ve negative testleri ayrı tut. Parametreyi testte explicit set et. Testler başka şirket/veri durumuna bağımlı olmamalı.',source:src.unit},
    review:{title:'Code review: yavaş ve riskli maintenance kodu',context:'PR 80.000 kaydı loop içinde güncelliyor, doUpdate() kullanıyor ve tüm transaction’ı tek tts içine alıyor.',problem:'Business logic bypass, lock süresi ve ölçeklenebilirlik riski birlikte var.',request:'Riskleri severity ile işaretle ve güvenli redesign öner.',question:'Kod inceleme notunu yaz.',starter:`ttsBegin;\nwhile select forUpdate myTable\n{\n    myTable.Flag = NoYes::Yes;\n    myTable.doUpdate();\n}\nttsCommit;\n\n// Review notes:\n`,checks:[['doUpdate',/doUpdate|bypass/i,'doUpdate bypass riski yakalandı mı?'],['lock',/lock|tts|transaction/i,'Uzun transaction/lock riski yakalandı mı?'],['set',/set-based|update_recordset|batch|chunk/i,'Alternatif tasarım önerildi mi?']],solution:'High: doUpdate standard logic/events/CoC bypass eder. High: dev transaction lock süresini büyütür. Önce update() logic gereksinimini analiz et; uygunsa set-based, değilse kontrollü chunk + idempotent batch + retry stratejisi.',source:src.update},
    capstone:{title:'Capstone: PO üzerinde zorunlu bütçe gerekçe kodu',context:'Procurement, 50.000 TRY üstü PO confirm edilirken BudgetJustification alanı zorunlu olsun; Data Entity ve batch confirm de aynı kurala uysun.',problem:'UI-only çözüm tüm entry point’leri korumaz. Hardcode threshold sürdürülebilir değildir.',request:'Standard-vs-custom analizi, metadata, extension point, parameter, security, test ve performance planı çıkar.',question:'Bir mini technical design yaz.',starter:`1. Standard fit/gap:\n2. Configuration/parameter:\n3. Metadata extension:\n4. Business validation point:\n5. Integration impact:\n6. Security:\n7. Tests:\n8. Performance/rollback:\n`,checks:[['fitgap',/fit|standard|configuration/i,'Standard/fit-gap analizi var mı?'],['extension',/extension|CoC|event/i,'Upgrade-safe extension yaklaşımı var mı?'],['integration',/entity|odata|integration|batch/i,'Diğer entry pointler düşünülmüş mü?'],['test',/test|uat|boundary/i,'Test planı var mı?'],['perf',/performance|query|lock|transaction/i,'Performance düşünülmüş mü?']],solution:'Önce standard workflow/budget controls ile ihtiyacın karşılanıp karşılanmadığını doğrula. Custom gerekirse parameterized threshold + PO extension field + business-layer validation extension + entity coverage + privilege + boundary/unit/UAT testleri + telemetry/rollback planı.',source:src.ext}
  };
  function renderHome(){
    const done=Object.values(s.done).filter(Boolean).length;
    set(`<div class="p5-hero"><div class="p5-panel"><h1>X++ Developer Lab · Faz 5</h1><p>Hedef: X++ syntax öğrenmekten öte, <b>mid-level D365FO developer düşünme biçimi</b>: doğru extension point, transaction integrity, performans, test ve techno-functional tasarım.</p><div class="p5-callout"><b>Önemli:</b> Bu browser lab gerçek X++ compiler değildir. Kod editörü ve analyzer öğreticidir; gerçek compile/debug için desteklenen D365FO developer environment gerekir.</div><div class="p5-pipeline"><span class="p5-stage">Requirement</span><span class="p5-arrow">→</span><span class="p5-stage">Standard fit-gap</span><span class="p5-arrow">→</span><span class="p5-stage">Design</span><span class="p5-arrow">→</span><span class="p5-stage">X++</span><span class="p5-arrow">→</span><span class="p5-stage">Test</span><span class="p5-arrow">→</span><span class="p5-stage">Review</span></div></div><div class="p5-panel"><h3>İlerleme</h3><div class="p5-score">${pct()}%</div><p>${done}/${lessons.length} lab tamamlandı</p><button class="cmd primary" id="p5continue">Devam et</button><button class="cmd" id="p5reset">Faz 5 ilerlemeyi sıfırla</button></div></div><div class="p5-kpis"><div class="p5-kpi">Performance<b>N+1 / set-based</b></div><div class="p5-kpi">Integrity<b>tts / concurrency</b></div><div class="p5-kpi">Extensibility<b>CoC / extension</b></div><div class="p5-kpi">Delivery<b>test / review</b></div></div><h2>12 adımlık developer yolu</h2><div class="p5-path">${lessons.map(l=>`<div class="p5-lesson ${s.done[l.id]?'done':''}" data-p5="${l.id}"><div class="p5-num">${l.n}</div><div><b>${l.title}</b><div>${l.desc}</div><span class="p5-badge">${l.level}</span></div></div>`).join('')}</div>`,`Developer > X++ Developer Lab`);
    document.querySelectorAll('[data-p5]').forEach(x=>x.onclick=()=>renderLab(x.dataset.p5));
    document.querySelector('#p5continue').onclick=()=>renderLab(lessons.find(l=>!s.done[l.id])?.id||'capstone');
    document.querySelector('#p5reset').onclick=()=>{if(confirm('Faz 5 ilerlemesi sıfırlansın mı?')){s=seed();save();renderHome()}};
  }
  function renderLab(id){
    const l=lessons.find(x=>x.id===id),lab=labs[id]; if(!l||!lab)return renderHome();s.last=id;save();
    const note=s.notes[id]||lab.starter;
    set(`<div class="p5-panel"><button class="cmd" id="p5back">← Developer yolu</button><span class="p5-badge">${l.level}</span><h1>${l.n}. ${l.title}</h1><p>${l.desc}</p><div class="p5-meta"><div><b>Menü/teknik alan</b><br>${l.path}</div><div><b>Hedef</b><br>Doğru tasarım + çalışan mantık + review</div><div><b>Durum</b><br>${s.done[id]?'Tamamlandı':'Çalışılıyor'}</div></div></div><div class="p5-context"><div><h4>İş bağlamı</h4>${lab.context}</div><div><h4>Sorun / risk</h4>${lab.problem}</div><div><h4>Şirketin isteği</h4>${lab.request}</div><div><h4>Sana sorulan</h4>${lab.question}</div></div><div class="p5-codegrid"><div class="p5-codecard"><h3>Çalışma alanın</h3><textarea id="p5editor" class="p5-editor" spellcheck="false">${esc(note)}</textarea><div class="commandbar"><button class="cmd primary" id="p5analyze">Analyze / Review</button><button class="cmd" id="p5save">Kaydet</button><button class="cmd" id="p5hint">İpucu</button><button class="cmd" id="p5solution">Referans yaklaşım</button></div><div id="p5out" class="p5-output">Kodunu veya teknik tasarımını yaz; sonra Analyze / Review çalıştır.</div></div><div class="p5-codecard"><h3>Mid-level checklist</h3><div class="p5-check">□ Standard çözüm önce değerlendirildi mi?</div><div class="p5-check">□ Doğru business boundary seçildi mi?</div><div class="p5-check">□ Upgrade-safe extension mı?</div><div class="p5-check">□ Query/transaction ölçeklenebilir mi?</div><div class="p5-check">□ Security ve integration entry pointleri kapsanıyor mu?</div><div class="p5-check">□ Negative/boundary test var mı?</div><div class="p5-danger"><b>Anti-pattern:</b> UI-only validation, hardcode company/user, System administrator ile problemi kapatma, doUpdate() ile business logic bypass, devasa tts scope.</div><a class="p5-source" target="_blank" rel="noopener" href="${lab.source}">Microsoft Learn kaynağı ↗</a></div></div>`,`Developer > X++ Developer Lab > ${l.title}`);
    document.querySelector('#p5back').onclick=renderHome;
    document.querySelector('#p5save').onclick=()=>{s.notes[id]=document.querySelector('#p5editor').value;save();out('Kaydedildi.','ok')};
    document.querySelector('#p5hint').onclick=()=>out('İpucu: önce gereksinimin hangi entry pointlerden çalıştığını düşün. Sonra invariant nerede yaşamalı, transaction/query maliyeti ne, upgrade-safe extension point hangisi?','warn');
    document.querySelector('#p5solution').onclick=()=>out(`<b>Referans yaklaşım:</b><pre class="dev5-code p5-code">${esc(lab.solution)}</pre>`,'ok');
    document.querySelector('#p5analyze').onclick=()=>analyze(id);
  }
  function out(html,kind=''){const e=document.querySelector('#p5out');if(e)e.innerHTML=`<div class="p5-check ${kind}">${html}</div>`}
  function analyze(id){const lab=labs[id],code=document.querySelector('#p5editor').value;s.notes[id]=code;s.attempts[id]=(s.attempts[id]||0)+1;let pass=0;const rows=lab.checks.map(([k,re,label])=>{const ok=re.test(code);if(ok)pass++;return `<div class="p5-check ${ok?'ok':'bad'}">${ok?'✓':'✗'} ${label}</div>`}).join('');const pct2=Math.round(pass/lab.checks.length*100);if(pct2===100)s.done[id]=true;save();document.querySelector('#p5out').innerHTML=`<b>Review skoru: ${pct2}%</b>${rows}${pct2===100?'<div class="p5-solution"><b>Lab tamamlandı.</b> Şimdi referans yaklaşımı açıp kendi çözümünle farkları incele.</div>':'<div class="p5-hint">Eksik maddeleri düzelt. Analyzer gerçek compiler değildir; pattern-based eğitim kontrolüdür.</div>'}`}
  function install(){
    const oldRender=window.render;
    if(typeof oldRender==='function')window.render=function(name){if(name==='xppDeveloper'||name==='phase5')return renderHome();return oldRender(name)};
    const oldModules=window.renderModules;
    if(typeof oldModules==='function')window.renderModules=function(){oldModules();setTimeout(()=>{const nc=document.querySelector('#navContent');if(nc&&!nc.querySelector('[data-page="xppDeveloper"]')){const g=document.createElement('div');g.className='nav-group';g.innerHTML='<h4>Developer · Faz 5</h4><button class="nav-link" data-page="xppDeveloper">X++ Developer Lab</button>';nc.appendChild(g);g.querySelector('button').onclick=()=>window.render('xppDeveloper')}},0)};
    const oldHome=window.renderHome;
    if(typeof oldHome==='function')window.renderHome=function(){oldHome();setTimeout(()=>{const host=document.querySelector('.menu-columns')||document.querySelector('.cards');if(host&&!document.querySelector('[data-page="xppDeveloper"]')){const box=document.createElement('div');box.className='menu-box';box.innerHTML='<h3>Developer · Faz 5</h3><button data-page="xppDeveloper">X++ Developer Lab</button><div class="muted">12 lab · Foundation → Mid+</div>';host.appendChild(box);box.querySelector('button').onclick=()=>window.render('xppDeveloper')}},0)};
    document.querySelectorAll('.rail-btn[data-nav="xpp"]').forEach(b=>b.onclick=()=>renderHome());
  }
  window.phase5={renderHome,renderLab,version:VERSION};
  install();
})();
